# SConscript
# Build file for the dtest of the nvm_controller app.
# 
# Copyright 2014 Gram Power, Inc.

Import('env')
env.Append(CPPPATH=['.', '..', '../mocks'])

# Create the test program
env.Program('dtest', env['DEFAULT_SOURCE_FILES'] + ['nvm_controller_app_dtest.cpp', '../nvm_controller_app.cpp'])
